### PR TITLE
Adding automake support for sgxtop.

### PR DESCRIPTION
**Pull request by vishwas-ftx**
* **configure** is auto-generated file, but this has been checked-in to allow folks without autoconf/automake to build and use the tool.

* : ${CFLAGS="-O0  -g"}  - in configure.ac can be changed after perf build issues are resolved.

### CODE REVIEW

**Comment by kevinlahey** [comment]
Awesome, thanks!  I certainly appreciate it.

The ./configure didn't work for me -- perhaps we should exclude that?  It sounds like folks would have to do an "autoreconf -f" anyway, right?

(I could also imagine getting rid of build.sh and cleanup.sh [or change cleanup.sh to take care of all of the autotools files]).

I'm willing to merge this whether or not you make those changes, though, so let me know.

**Comment by vishwas-ftx** [comment]
> Awesome, thanks! I certainly appreciate it.
> 
> The ./configure didn't work for me -- perhaps we should exclude that? It sounds like folks would have to do an "autoreconf -f" anyway, right?
> 
> (I could also imagine getting rid of build.sh and cleanup.sh [or change cleanup.sh to take care of all of the autotools files]).
> 
> I'm willing to merge this whether or not you make those changes, though, so let me know.

Removed configure/build/cleanup and updated maintainer.sh

**Review by kevinlahey — APPROVED** [review]
Looks good -- if you can resolve that last Makefile issue (I was a little surprised it complained about that, since we're deleting the file), let's get this committed!  (And if you want, I'm happy to resolve the diff, but figured I wouldn't mess with your commit.

**Comment by vishwas-ftx** [comment]
> Looks good -- if you can resolve that last Makefile issue (I was a little surprised it complained about that, since we're deleting the file), let's get this committed! (And if you want, I'm happy to resolve the diff, but figured I wouldn't mess with your commit.

Addressed the Makefile merge.

**Pull request merged**
